version: "3.7"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing:${SYNCTHING_VERSION}
    container_name: syncthing
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${SYNCTHING_CONFIG_PATH}:/config
      - ${DEVICES_STORAGE_PATH}:/devices
      - ${MEDIA_STORAGE_PATH}:/media_data
    ports:
      - ${SYNCTHING_WEB_PORT}:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp

  resilio-sync:
    image: ghcr.io/linuxserver/resilio-sync:${RESILIO_SYNC_VERSION}
    container_name: resilio-sync
    hostname: ${HOSTNAME}
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${RESILIO_CONFIG_PATH}:/config
      - ${DEVICES_STORAGE_PATH}:/devices
    ports:
      - ${RESILIO_WEB_PORT}:8888
      - 55555:55555

  duplicacy:
    image: 'saspus/duplicacy-web:${DUPLICACY_VERSION}'
    container_name: duplicacy
    hostname: ${HOSTNAME}
    restart: unless-stopped
    ports:
        - '${DUPLICACY_WEB_PORT}:3875/tcp'
    environment:
      - TZ=Europe/Moscow
      - GRP_ID=1000
      - USR_ID:1000
    volumes:
        - '${DUPLICACY_CONFIG_PATH}:/config'
        - '${DUPLICACY_LOGS_PATH}:/logs'
        - '${DUPLICACY_CACHE_PATH}/cache'
        - '${DUPLICACY_RESTORE_PATH}:/backuproot'
        - '${BACKUP_STORAGE_PATH}:/storage:ro'
  crontab-ui:
    image: ghcr.io/ephdtrg/crontab-ui-rclone:rclone
    container_name: crontab-ui
    restart: unless-stopped
    ports:
      - ${CRONTAB_UI_WEB_PORT}:8000
    environment:
      - TZ=Europe/Moscow
      # - BASIC_AUTH_USER=${CRONTAB_UI_USER}
      # - BASIC_AUTH_PWD=${CRONTAB_UI_PASSWORD}
    volumes:
      - ${CRONTAB_UI_DB_PATH}:/crontab-ui/crontabs
      - ${CRONTAB_UI_LOGS_PATH}:/crontab-ui/crontabs/logs
      - ${CRONTAB_UI_SUPERVISOR_LOGS_PATH}:/var/log
      - ${CRONTAB_UI_CRONS_PATH}:/etc/crontabs
      - ${CRONTAB_UI_RCLONE_CONFIG}:/root/.config/rclone/rclone.conf:ro
      - ${BACKUP_STORAGE_PATH}:${BACKUP_STORAGE_PATH}:ro